#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTNETTHANGTIEN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THUCHANHDOTNET1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBANGDIEM(BANGDIEM instance);
    partial void UpdateBANGDIEM(BANGDIEM instance);
    partial void DeleteBANGDIEM(BANGDIEM instance);
    partial void InsertBANGMONHOC(BANGMONHOC instance);
    partial void UpdateBANGMONHOC(BANGMONHOC instance);
    partial void DeleteBANGMONHOC(BANGMONHOC instance);
    partial void InsertBANGGIAOVIEN(BANGGIAOVIEN instance);
    partial void UpdateBANGGIAOVIEN(BANGGIAOVIEN instance);
    partial void DeleteBANGGIAOVIEN(BANGGIAOVIEN instance);
    partial void InsertBANGHOCSINH(BANGHOCSINH instance);
    partial void UpdateBANGHOCSINH(BANGHOCSINH instance);
    partial void DeleteBANGHOCSINH(BANGHOCSINH instance);
    partial void InsertBANGKHOI(BANGKHOI instance);
    partial void UpdateBANGKHOI(BANGKHOI instance);
    partial void DeleteBANGKHOI(BANGKHOI instance);
    partial void InsertBANGLOPHOC(BANGLOPHOC instance);
    partial void UpdateBANGLOPHOC(BANGLOPHOC instance);
    partial void DeleteBANGLOPHOC(BANGLOPHOC instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DOTNETTHANGTIEN.Properties.Settings.Default.THUCHANHDOTNET1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<BANGDIEM> BANGDIEMs
		{
			get
			{
				return this.GetTable<BANGDIEM>();
			}
		}
		
		public System.Data.Linq.Table<BANGMONHOC> BANGMONHOCs
		{
			get
			{
				return this.GetTable<BANGMONHOC>();
			}
		}
		
		public System.Data.Linq.Table<BANGGIAOVIEN> BANGGIAOVIENs
		{
			get
			{
				return this.GetTable<BANGGIAOVIEN>();
			}
		}
		
		public System.Data.Linq.Table<BANGHOCSINH> BANGHOCSINHs
		{
			get
			{
				return this.GetTable<BANGHOCSINH>();
			}
		}
		
		public System.Data.Linq.Table<BANGKHOI> BANGKHOIs
		{
			get
			{
				return this.GetTable<BANGKHOI>();
			}
		}
		
		public System.Data.Linq.Table<BANGLOPHOC> BANGLOPHOCs
		{
			get
			{
				return this.GetTable<BANGLOPHOC>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT
	{
		
		private string _User;
		
		private string _Password;
		
		private string _Role;
		
		public ACCOUNT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGDIEM")]
	public partial class BANGDIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Mã_học_sinh;
		
		private string _Mã_môn_học;
		
		private int _Điểm_giữa_kì_1_I;
		
		private int _Điểm_cuối_kì_1_I;
		
		private System.Nullable<int> _Điểm_giữa_kì_2_I;
		
		private System.Nullable<int> _Điểm_cuối_kì_2_I;
		
		private System.Nullable<int> _Điểm_giữa_kì_3_II;
		
		private System.Nullable<int> _Điểm_cuối_kì_3_II;
		
		private System.Nullable<int> _Điểm_giữa_kì_4_II;
		
		private System.Nullable<int> _Điểm_cuối_kì_4_II;
		
		private System.Nullable<int> _Điểm_giữa_kì_5_III;
		
		private System.Nullable<int> _Điểm_cuối_kì_5_III;
		
		private System.Nullable<int> _Điểm_giữa_kì_6_III;
		
		private System.Nullable<int> _Điểm_cuối_kì_6_III;
		
		private System.Nullable<int> _Điểm_giữa_kì_7_IV;
		
		private System.Nullable<int> _Điểm_cuối_kì_7_IV;
		
		private System.Nullable<int> _Điểm_giữa_kì_8_IV;
		
		private System.Nullable<int> _Điểm_cuối_kì_8_IV;
		
		private System.Nullable<int> _Điểm_giũa_kì_9_V;
		
		private System.Nullable<int> _Điểm_cuối_kì_9_V;
		
		private System.Nullable<int> _Điểm_giữa_kì_10_V;
		
		private System.Nullable<int> _Điểm_cuối_kì_10_V;
		
		private EntityRef<BANGMONHOC> _BANGMONHOC;
		
		private EntityRef<BANGHOCSINH> _BANGHOCSINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnMã_học_sinhChanging(string value);
    partial void OnMã_học_sinhChanged();
    partial void OnMã_môn_họcChanging(string value);
    partial void OnMã_môn_họcChanged();
    partial void OnĐiểm_giữa_kì_1_IChanging(int value);
    partial void OnĐiểm_giữa_kì_1_IChanged();
    partial void OnĐiểm_cuối_kì_1_IChanging(int value);
    partial void OnĐiểm_cuối_kì_1_IChanged();
    partial void OnĐiểm_giữa_kì_2_IChanging(System.Nullable<int> value);
    partial void OnĐiểm_giữa_kì_2_IChanged();
    partial void OnĐiểm_cuối_kì_2_IChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_2_IChanged();
    partial void OnĐiểm_giữa_kì_3_IIChanging(System.Nullable<int> value);
    partial void OnĐiểm_giữa_kì_3_IIChanged();
    partial void OnĐiểm_cuối_kì_3_IIChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_3_IIChanged();
    partial void OnĐiểm_giữa_kì_4_IIChanging(System.Nullable<int> value);
    partial void OnĐiểm_giữa_kì_4_IIChanged();
    partial void OnĐiểm_cuối_kì_4_IIChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_4_IIChanged();
    partial void OnĐiểm_giữa_kì_5_IIIChanging(System.Nullable<int> value);
    partial void OnĐiểm_giữa_kì_5_IIIChanged();
    partial void OnĐiểm_cuối_kì_5_IIIChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_5_IIIChanged();
    partial void OnĐiểm_giữa_kì_6_IIIChanging(System.Nullable<int> value);
    partial void OnĐiểm_giữa_kì_6_IIIChanged();
    partial void OnĐiểm_cuối_kì_6_IIIChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_6_IIIChanged();
    partial void OnĐiểm_giữa_kì_7_IVChanging(System.Nullable<int> value);
    partial void OnĐiểm_giữa_kì_7_IVChanged();
    partial void OnĐiểm_cuối_kì_7_IVChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_7_IVChanged();
    partial void OnĐiểm_giữa_kì_8_IVChanging(System.Nullable<int> value);
    partial void OnĐiểm_giữa_kì_8_IVChanged();
    partial void OnĐiểm_cuối_kì_8_IVChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_8_IVChanged();
    partial void OnĐiểm_giũa_kì_9_VChanging(System.Nullable<int> value);
    partial void OnĐiểm_giũa_kì_9_VChanged();
    partial void OnĐiểm_cuối_kì_9_VChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_9_VChanged();
    partial void OnĐiểm_giữa_kì_10_VChanging(System.Nullable<int> value);
    partial void OnĐiểm_giữa_kì_10_VChanged();
    partial void OnĐiểm_cuối_kì_10_VChanging(System.Nullable<int> value);
    partial void OnĐiểm_cuối_kì_10_VChanged();
    #endregion
		
		public BANGDIEM()
		{
			this._BANGMONHOC = default(EntityRef<BANGMONHOC>);
			this._BANGHOCSINH = default(EntityRef<BANGHOCSINH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã học sinh]", Storage="_Mã_học_sinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_học_sinh
		{
			get
			{
				return this._Mã_học_sinh;
			}
			set
			{
				if ((this._Mã_học_sinh != value))
				{
					this.OnMã_học_sinhChanging(value);
					this.SendPropertyChanging();
					this._Mã_học_sinh = value;
					this.SendPropertyChanged("Mã_học_sinh");
					this.OnMã_học_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã môn học]", Storage="_Mã_môn_học", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_môn_học
		{
			get
			{
				return this._Mã_môn_học;
			}
			set
			{
				if ((this._Mã_môn_học != value))
				{
					this.OnMã_môn_họcChanging(value);
					this.SendPropertyChanging();
					this._Mã_môn_học = value;
					this.SendPropertyChanged("Mã_môn_học");
					this.OnMã_môn_họcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 1_I]", Storage="_Điểm_giữa_kì_1_I", DbType="Int NOT NULL")]
		public int Điểm_giữa_kì_1_I
		{
			get
			{
				return this._Điểm_giữa_kì_1_I;
			}
			set
			{
				if ((this._Điểm_giữa_kì_1_I != value))
				{
					this.OnĐiểm_giữa_kì_1_IChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_1_I = value;
					this.SendPropertyChanged("Điểm_giữa_kì_1_I");
					this.OnĐiểm_giữa_kì_1_IChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 1_I]", Storage="_Điểm_cuối_kì_1_I", DbType="Int NOT NULL")]
		public int Điểm_cuối_kì_1_I
		{
			get
			{
				return this._Điểm_cuối_kì_1_I;
			}
			set
			{
				if ((this._Điểm_cuối_kì_1_I != value))
				{
					this.OnĐiểm_cuối_kì_1_IChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_1_I = value;
					this.SendPropertyChanged("Điểm_cuối_kì_1_I");
					this.OnĐiểm_cuối_kì_1_IChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 2_I]", Storage="_Điểm_giữa_kì_2_I", DbType="Int")]
		public System.Nullable<int> Điểm_giữa_kì_2_I
		{
			get
			{
				return this._Điểm_giữa_kì_2_I;
			}
			set
			{
				if ((this._Điểm_giữa_kì_2_I != value))
				{
					this.OnĐiểm_giữa_kì_2_IChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_2_I = value;
					this.SendPropertyChanged("Điểm_giữa_kì_2_I");
					this.OnĐiểm_giữa_kì_2_IChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 2_I]", Storage="_Điểm_cuối_kì_2_I", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_2_I
		{
			get
			{
				return this._Điểm_cuối_kì_2_I;
			}
			set
			{
				if ((this._Điểm_cuối_kì_2_I != value))
				{
					this.OnĐiểm_cuối_kì_2_IChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_2_I = value;
					this.SendPropertyChanged("Điểm_cuối_kì_2_I");
					this.OnĐiểm_cuối_kì_2_IChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 3_II]", Storage="_Điểm_giữa_kì_3_II", DbType="Int")]
		public System.Nullable<int> Điểm_giữa_kì_3_II
		{
			get
			{
				return this._Điểm_giữa_kì_3_II;
			}
			set
			{
				if ((this._Điểm_giữa_kì_3_II != value))
				{
					this.OnĐiểm_giữa_kì_3_IIChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_3_II = value;
					this.SendPropertyChanged("Điểm_giữa_kì_3_II");
					this.OnĐiểm_giữa_kì_3_IIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 3_II]", Storage="_Điểm_cuối_kì_3_II", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_3_II
		{
			get
			{
				return this._Điểm_cuối_kì_3_II;
			}
			set
			{
				if ((this._Điểm_cuối_kì_3_II != value))
				{
					this.OnĐiểm_cuối_kì_3_IIChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_3_II = value;
					this.SendPropertyChanged("Điểm_cuối_kì_3_II");
					this.OnĐiểm_cuối_kì_3_IIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 4_II]", Storage="_Điểm_giữa_kì_4_II", DbType="Int")]
		public System.Nullable<int> Điểm_giữa_kì_4_II
		{
			get
			{
				return this._Điểm_giữa_kì_4_II;
			}
			set
			{
				if ((this._Điểm_giữa_kì_4_II != value))
				{
					this.OnĐiểm_giữa_kì_4_IIChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_4_II = value;
					this.SendPropertyChanged("Điểm_giữa_kì_4_II");
					this.OnĐiểm_giữa_kì_4_IIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 4_II]", Storage="_Điểm_cuối_kì_4_II", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_4_II
		{
			get
			{
				return this._Điểm_cuối_kì_4_II;
			}
			set
			{
				if ((this._Điểm_cuối_kì_4_II != value))
				{
					this.OnĐiểm_cuối_kì_4_IIChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_4_II = value;
					this.SendPropertyChanged("Điểm_cuối_kì_4_II");
					this.OnĐiểm_cuối_kì_4_IIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 5_III]", Storage="_Điểm_giữa_kì_5_III", DbType="Int")]
		public System.Nullable<int> Điểm_giữa_kì_5_III
		{
			get
			{
				return this._Điểm_giữa_kì_5_III;
			}
			set
			{
				if ((this._Điểm_giữa_kì_5_III != value))
				{
					this.OnĐiểm_giữa_kì_5_IIIChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_5_III = value;
					this.SendPropertyChanged("Điểm_giữa_kì_5_III");
					this.OnĐiểm_giữa_kì_5_IIIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 5_III]", Storage="_Điểm_cuối_kì_5_III", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_5_III
		{
			get
			{
				return this._Điểm_cuối_kì_5_III;
			}
			set
			{
				if ((this._Điểm_cuối_kì_5_III != value))
				{
					this.OnĐiểm_cuối_kì_5_IIIChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_5_III = value;
					this.SendPropertyChanged("Điểm_cuối_kì_5_III");
					this.OnĐiểm_cuối_kì_5_IIIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 6_III]", Storage="_Điểm_giữa_kì_6_III", DbType="Int")]
		public System.Nullable<int> Điểm_giữa_kì_6_III
		{
			get
			{
				return this._Điểm_giữa_kì_6_III;
			}
			set
			{
				if ((this._Điểm_giữa_kì_6_III != value))
				{
					this.OnĐiểm_giữa_kì_6_IIIChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_6_III = value;
					this.SendPropertyChanged("Điểm_giữa_kì_6_III");
					this.OnĐiểm_giữa_kì_6_IIIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 6_III]", Storage="_Điểm_cuối_kì_6_III", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_6_III
		{
			get
			{
				return this._Điểm_cuối_kì_6_III;
			}
			set
			{
				if ((this._Điểm_cuối_kì_6_III != value))
				{
					this.OnĐiểm_cuối_kì_6_IIIChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_6_III = value;
					this.SendPropertyChanged("Điểm_cuối_kì_6_III");
					this.OnĐiểm_cuối_kì_6_IIIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 7_IV]", Storage="_Điểm_giữa_kì_7_IV", DbType="Int")]
		public System.Nullable<int> Điểm_giữa_kì_7_IV
		{
			get
			{
				return this._Điểm_giữa_kì_7_IV;
			}
			set
			{
				if ((this._Điểm_giữa_kì_7_IV != value))
				{
					this.OnĐiểm_giữa_kì_7_IVChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_7_IV = value;
					this.SendPropertyChanged("Điểm_giữa_kì_7_IV");
					this.OnĐiểm_giữa_kì_7_IVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 7_IV]", Storage="_Điểm_cuối_kì_7_IV", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_7_IV
		{
			get
			{
				return this._Điểm_cuối_kì_7_IV;
			}
			set
			{
				if ((this._Điểm_cuối_kì_7_IV != value))
				{
					this.OnĐiểm_cuối_kì_7_IVChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_7_IV = value;
					this.SendPropertyChanged("Điểm_cuối_kì_7_IV");
					this.OnĐiểm_cuối_kì_7_IVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 8_IV]", Storage="_Điểm_giữa_kì_8_IV", DbType="Int")]
		public System.Nullable<int> Điểm_giữa_kì_8_IV
		{
			get
			{
				return this._Điểm_giữa_kì_8_IV;
			}
			set
			{
				if ((this._Điểm_giữa_kì_8_IV != value))
				{
					this.OnĐiểm_giữa_kì_8_IVChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_8_IV = value;
					this.SendPropertyChanged("Điểm_giữa_kì_8_IV");
					this.OnĐiểm_giữa_kì_8_IVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 8_IV]", Storage="_Điểm_cuối_kì_8_IV", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_8_IV
		{
			get
			{
				return this._Điểm_cuối_kì_8_IV;
			}
			set
			{
				if ((this._Điểm_cuối_kì_8_IV != value))
				{
					this.OnĐiểm_cuối_kì_8_IVChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_8_IV = value;
					this.SendPropertyChanged("Điểm_cuối_kì_8_IV");
					this.OnĐiểm_cuối_kì_8_IVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giũa kì 9_V]", Storage="_Điểm_giũa_kì_9_V", DbType="Int")]
		public System.Nullable<int> Điểm_giũa_kì_9_V
		{
			get
			{
				return this._Điểm_giũa_kì_9_V;
			}
			set
			{
				if ((this._Điểm_giũa_kì_9_V != value))
				{
					this.OnĐiểm_giũa_kì_9_VChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giũa_kì_9_V = value;
					this.SendPropertyChanged("Điểm_giũa_kì_9_V");
					this.OnĐiểm_giũa_kì_9_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 9_V]", Storage="_Điểm_cuối_kì_9_V", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_9_V
		{
			get
			{
				return this._Điểm_cuối_kì_9_V;
			}
			set
			{
				if ((this._Điểm_cuối_kì_9_V != value))
				{
					this.OnĐiểm_cuối_kì_9_VChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_9_V = value;
					this.SendPropertyChanged("Điểm_cuối_kì_9_V");
					this.OnĐiểm_cuối_kì_9_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm giữa kì 10_V]", Storage="_Điểm_giữa_kì_10_V", DbType="Int")]
		public System.Nullable<int> Điểm_giữa_kì_10_V
		{
			get
			{
				return this._Điểm_giữa_kì_10_V;
			}
			set
			{
				if ((this._Điểm_giữa_kì_10_V != value))
				{
					this.OnĐiểm_giữa_kì_10_VChanging(value);
					this.SendPropertyChanging();
					this._Điểm_giữa_kì_10_V = value;
					this.SendPropertyChanged("Điểm_giữa_kì_10_V");
					this.OnĐiểm_giữa_kì_10_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Điểm cuối kì 10_V]", Storage="_Điểm_cuối_kì_10_V", DbType="Int")]
		public System.Nullable<int> Điểm_cuối_kì_10_V
		{
			get
			{
				return this._Điểm_cuối_kì_10_V;
			}
			set
			{
				if ((this._Điểm_cuối_kì_10_V != value))
				{
					this.OnĐiểm_cuối_kì_10_VChanging(value);
					this.SendPropertyChanging();
					this._Điểm_cuối_kì_10_V = value;
					this.SendPropertyChanged("Điểm_cuối_kì_10_V");
					this.OnĐiểm_cuối_kì_10_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGMONHOC_BANGDIEM", Storage="_BANGMONHOC", ThisKey="Mã_môn_học", OtherKey="Mã_môn_học", IsForeignKey=true)]
		public BANGMONHOC BANGMONHOC
		{
			get
			{
				return this._BANGMONHOC.Entity;
			}
			set
			{
				BANGMONHOC previousValue = this._BANGMONHOC.Entity;
				if (((previousValue != value) 
							|| (this._BANGMONHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANGMONHOC.Entity = null;
						previousValue.BANGDIEMs.Remove(this);
					}
					this._BANGMONHOC.Entity = value;
					if ((value != null))
					{
						value.BANGDIEMs.Add(this);
						this._Mã_môn_học = value.Mã_môn_học;
					}
					else
					{
						this._Mã_môn_học = default(string);
					}
					this.SendPropertyChanged("BANGMONHOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGHOCSINH_BANGDIEM", Storage="_BANGHOCSINH", ThisKey="Mã_học_sinh", OtherKey="Mã_học_sinh", IsForeignKey=true)]
		public BANGHOCSINH BANGHOCSINH
		{
			get
			{
				return this._BANGHOCSINH.Entity;
			}
			set
			{
				BANGHOCSINH previousValue = this._BANGHOCSINH.Entity;
				if (((previousValue != value) 
							|| (this._BANGHOCSINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANGHOCSINH.Entity = null;
						previousValue.BANGDIEMs.Remove(this);
					}
					this._BANGHOCSINH.Entity = value;
					if ((value != null))
					{
						value.BANGDIEMs.Add(this);
						this._Mã_học_sinh = value.Mã_học_sinh;
					}
					else
					{
						this._Mã_học_sinh = default(string);
					}
					this.SendPropertyChanged("BANGHOCSINH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGMONHOC")]
	public partial class BANGMONHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_môn_học;
		
		private string _Tên_môn_học;
		
		private int _Hệ_số_môn_học;
		
		private EntitySet<BANGDIEM> _BANGDIEMs;
		
		private EntitySet<BANGGIAOVIEN> _BANGGIAOVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_môn_họcChanging(string value);
    partial void OnMã_môn_họcChanged();
    partial void OnTên_môn_họcChanging(string value);
    partial void OnTên_môn_họcChanged();
    partial void OnHệ_số_môn_họcChanging(int value);
    partial void OnHệ_số_môn_họcChanged();
    #endregion
		
		public BANGMONHOC()
		{
			this._BANGDIEMs = new EntitySet<BANGDIEM>(new Action<BANGDIEM>(this.attach_BANGDIEMs), new Action<BANGDIEM>(this.detach_BANGDIEMs));
			this._BANGGIAOVIENs = new EntitySet<BANGGIAOVIEN>(new Action<BANGGIAOVIEN>(this.attach_BANGGIAOVIENs), new Action<BANGGIAOVIEN>(this.detach_BANGGIAOVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã môn học]", Storage="_Mã_môn_học", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_môn_học
		{
			get
			{
				return this._Mã_môn_học;
			}
			set
			{
				if ((this._Mã_môn_học != value))
				{
					this.OnMã_môn_họcChanging(value);
					this.SendPropertyChanging();
					this._Mã_môn_học = value;
					this.SendPropertyChanged("Mã_môn_học");
					this.OnMã_môn_họcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên môn học]", Storage="_Tên_môn_học", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tên_môn_học
		{
			get
			{
				return this._Tên_môn_học;
			}
			set
			{
				if ((this._Tên_môn_học != value))
				{
					this.OnTên_môn_họcChanging(value);
					this.SendPropertyChanging();
					this._Tên_môn_học = value;
					this.SendPropertyChanged("Tên_môn_học");
					this.OnTên_môn_họcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Hệ số môn học]", Storage="_Hệ_số_môn_học", DbType="Int NOT NULL")]
		public int Hệ_số_môn_học
		{
			get
			{
				return this._Hệ_số_môn_học;
			}
			set
			{
				if ((this._Hệ_số_môn_học != value))
				{
					this.OnHệ_số_môn_họcChanging(value);
					this.SendPropertyChanging();
					this._Hệ_số_môn_học = value;
					this.SendPropertyChanged("Hệ_số_môn_học");
					this.OnHệ_số_môn_họcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGMONHOC_BANGDIEM", Storage="_BANGDIEMs", ThisKey="Mã_môn_học", OtherKey="Mã_môn_học")]
		public EntitySet<BANGDIEM> BANGDIEMs
		{
			get
			{
				return this._BANGDIEMs;
			}
			set
			{
				this._BANGDIEMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGMONHOC_BANGGIAOVIEN", Storage="_BANGGIAOVIENs", ThisKey="Mã_môn_học", OtherKey="Mã_môn_học")]
		public EntitySet<BANGGIAOVIEN> BANGGIAOVIENs
		{
			get
			{
				return this._BANGGIAOVIENs;
			}
			set
			{
				this._BANGGIAOVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGDIEMs(BANGDIEM entity)
		{
			this.SendPropertyChanging();
			entity.BANGMONHOC = this;
		}
		
		private void detach_BANGDIEMs(BANGDIEM entity)
		{
			this.SendPropertyChanging();
			entity.BANGMONHOC = null;
		}
		
		private void attach_BANGGIAOVIENs(BANGGIAOVIEN entity)
		{
			this.SendPropertyChanging();
			entity.BANGMONHOC = this;
		}
		
		private void detach_BANGGIAOVIENs(BANGGIAOVIEN entity)
		{
			this.SendPropertyChanging();
			entity.BANGMONHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGGIAOVIEN")]
	public partial class BANGGIAOVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_giáo_viên;
		
		private string _Tên_giáo_viên;
		
		private System.Nullable<bool> _Chủ_nhiệm;
		
		private string _Mã_môn_học;
		
		private string _Mã_lớp;
		
		private EntitySet<BANGLOPHOC> _BANGLOPHOCs;
		
		private EntityRef<BANGMONHOC> _BANGMONHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_giáo_viênChanging(string value);
    partial void OnMã_giáo_viênChanged();
    partial void OnTên_giáo_viênChanging(string value);
    partial void OnTên_giáo_viênChanged();
    partial void OnChủ_nhiệmChanging(System.Nullable<bool> value);
    partial void OnChủ_nhiệmChanged();
    partial void OnMã_môn_họcChanging(string value);
    partial void OnMã_môn_họcChanged();
    partial void OnMã_lớpChanging(string value);
    partial void OnMã_lớpChanged();
    #endregion
		
		public BANGGIAOVIEN()
		{
			this._BANGLOPHOCs = new EntitySet<BANGLOPHOC>(new Action<BANGLOPHOC>(this.attach_BANGLOPHOCs), new Action<BANGLOPHOC>(this.detach_BANGLOPHOCs));
			this._BANGMONHOC = default(EntityRef<BANGMONHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã giáo viên]", Storage="_Mã_giáo_viên", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_giáo_viên
		{
			get
			{
				return this._Mã_giáo_viên;
			}
			set
			{
				if ((this._Mã_giáo_viên != value))
				{
					this.OnMã_giáo_viênChanging(value);
					this.SendPropertyChanging();
					this._Mã_giáo_viên = value;
					this.SendPropertyChanged("Mã_giáo_viên");
					this.OnMã_giáo_viênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên giáo viên]", Storage="_Tên_giáo_viên", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tên_giáo_viên
		{
			get
			{
				return this._Tên_giáo_viên;
			}
			set
			{
				if ((this._Tên_giáo_viên != value))
				{
					this.OnTên_giáo_viênChanging(value);
					this.SendPropertyChanging();
					this._Tên_giáo_viên = value;
					this.SendPropertyChanged("Tên_giáo_viên");
					this.OnTên_giáo_viênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Chủ nhiệm]", Storage="_Chủ_nhiệm", DbType="Bit")]
		public System.Nullable<bool> Chủ_nhiệm
		{
			get
			{
				return this._Chủ_nhiệm;
			}
			set
			{
				if ((this._Chủ_nhiệm != value))
				{
					this.OnChủ_nhiệmChanging(value);
					this.SendPropertyChanging();
					this._Chủ_nhiệm = value;
					this.SendPropertyChanged("Chủ_nhiệm");
					this.OnChủ_nhiệmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã môn học]", Storage="_Mã_môn_học", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_môn_học
		{
			get
			{
				return this._Mã_môn_học;
			}
			set
			{
				if ((this._Mã_môn_học != value))
				{
					this.OnMã_môn_họcChanging(value);
					this.SendPropertyChanging();
					this._Mã_môn_học = value;
					this.SendPropertyChanged("Mã_môn_học");
					this.OnMã_môn_họcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã lớp]", Storage="_Mã_lớp", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_lớp
		{
			get
			{
				return this._Mã_lớp;
			}
			set
			{
				if ((this._Mã_lớp != value))
				{
					this.OnMã_lớpChanging(value);
					this.SendPropertyChanging();
					this._Mã_lớp = value;
					this.SendPropertyChanged("Mã_lớp");
					this.OnMã_lớpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGGIAOVIEN_BANGLOPHOC", Storage="_BANGLOPHOCs", ThisKey="Mã_giáo_viên", OtherKey="Mã_giáo_viên")]
		public EntitySet<BANGLOPHOC> BANGLOPHOCs
		{
			get
			{
				return this._BANGLOPHOCs;
			}
			set
			{
				this._BANGLOPHOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGMONHOC_BANGGIAOVIEN", Storage="_BANGMONHOC", ThisKey="Mã_môn_học", OtherKey="Mã_môn_học", IsForeignKey=true)]
		public BANGMONHOC BANGMONHOC
		{
			get
			{
				return this._BANGMONHOC.Entity;
			}
			set
			{
				BANGMONHOC previousValue = this._BANGMONHOC.Entity;
				if (((previousValue != value) 
							|| (this._BANGMONHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANGMONHOC.Entity = null;
						previousValue.BANGGIAOVIENs.Remove(this);
					}
					this._BANGMONHOC.Entity = value;
					if ((value != null))
					{
						value.BANGGIAOVIENs.Add(this);
						this._Mã_môn_học = value.Mã_môn_học;
					}
					else
					{
						this._Mã_môn_học = default(string);
					}
					this.SendPropertyChanged("BANGMONHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGLOPHOCs(BANGLOPHOC entity)
		{
			this.SendPropertyChanging();
			entity.BANGGIAOVIEN = this;
		}
		
		private void detach_BANGLOPHOCs(BANGLOPHOC entity)
		{
			this.SendPropertyChanging();
			entity.BANGGIAOVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGHOCSINH")]
	public partial class BANGHOCSINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_học_sinh;
		
		private string _Tên_học_sinh;
		
		private string _Mã_lớp;
		
		private string _Mã_khối;
		
		private string _Mã_giáo_viên;
		
		private System.DateTime _Ngày_sinh;
		
		private bool _Giới_tính;
		
		private string _Hộ_khẩu_thường_trú;
		
		private string _Họ_và_tên_cha;
		
		private string _Nghề_nghiệp_cha;
		
		private string _Họ_và_tên_mẹ;
		
		private string _Nghề_nghiệp_mẹ;
		
		private bool _Sổ_hộ_nghèo;
		
		private bool _Khuyết_tật;
		
		private EntitySet<BANGDIEM> _BANGDIEMs;
		
		private EntityRef<BANGLOPHOC> _BANGLOPHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_học_sinhChanging(string value);
    partial void OnMã_học_sinhChanged();
    partial void OnTên_học_sinhChanging(string value);
    partial void OnTên_học_sinhChanged();
    partial void OnMã_lớpChanging(string value);
    partial void OnMã_lớpChanged();
    partial void OnMã_khốiChanging(string value);
    partial void OnMã_khốiChanged();
    partial void OnMã_giáo_viênChanging(string value);
    partial void OnMã_giáo_viênChanged();
    partial void OnNgày_sinhChanging(System.DateTime value);
    partial void OnNgày_sinhChanged();
    partial void OnGiới_tínhChanging(bool value);
    partial void OnGiới_tínhChanged();
    partial void OnHộ_khẩu_thường_trúChanging(string value);
    partial void OnHộ_khẩu_thường_trúChanged();
    partial void OnHọ_và_tên_chaChanging(string value);
    partial void OnHọ_và_tên_chaChanged();
    partial void OnNghề_nghiệp_chaChanging(string value);
    partial void OnNghề_nghiệp_chaChanged();
    partial void OnHọ_và_tên_mẹChanging(string value);
    partial void OnHọ_và_tên_mẹChanged();
    partial void OnNghề_nghiệp_mẹChanging(string value);
    partial void OnNghề_nghiệp_mẹChanged();
    partial void OnSổ_hộ_nghèoChanging(bool value);
    partial void OnSổ_hộ_nghèoChanged();
    partial void OnKhuyết_tậtChanging(bool value);
    partial void OnKhuyết_tậtChanged();
    #endregion
		
		public BANGHOCSINH()
		{
			this._BANGDIEMs = new EntitySet<BANGDIEM>(new Action<BANGDIEM>(this.attach_BANGDIEMs), new Action<BANGDIEM>(this.detach_BANGDIEMs));
			this._BANGLOPHOC = default(EntityRef<BANGLOPHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã học sinh]", Storage="_Mã_học_sinh", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_học_sinh
		{
			get
			{
				return this._Mã_học_sinh;
			}
			set
			{
				if ((this._Mã_học_sinh != value))
				{
					this.OnMã_học_sinhChanging(value);
					this.SendPropertyChanging();
					this._Mã_học_sinh = value;
					this.SendPropertyChanged("Mã_học_sinh");
					this.OnMã_học_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên học sinh]", Storage="_Tên_học_sinh", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Tên_học_sinh
		{
			get
			{
				return this._Tên_học_sinh;
			}
			set
			{
				if ((this._Tên_học_sinh != value))
				{
					this.OnTên_học_sinhChanging(value);
					this.SendPropertyChanging();
					this._Tên_học_sinh = value;
					this.SendPropertyChanged("Tên_học_sinh");
					this.OnTên_học_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã lớp]", Storage="_Mã_lớp", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_lớp
		{
			get
			{
				return this._Mã_lớp;
			}
			set
			{
				if ((this._Mã_lớp != value))
				{
					this.OnMã_lớpChanging(value);
					this.SendPropertyChanging();
					this._Mã_lớp = value;
					this.SendPropertyChanged("Mã_lớp");
					this.OnMã_lớpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã khối]", Storage="_Mã_khối", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_khối
		{
			get
			{
				return this._Mã_khối;
			}
			set
			{
				if ((this._Mã_khối != value))
				{
					this.OnMã_khốiChanging(value);
					this.SendPropertyChanging();
					this._Mã_khối = value;
					this.SendPropertyChanged("Mã_khối");
					this.OnMã_khốiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã giáo viên]", Storage="_Mã_giáo_viên", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_giáo_viên
		{
			get
			{
				return this._Mã_giáo_viên;
			}
			set
			{
				if ((this._Mã_giáo_viên != value))
				{
					this.OnMã_giáo_viênChanging(value);
					this.SendPropertyChanging();
					this._Mã_giáo_viên = value;
					this.SendPropertyChanged("Mã_giáo_viên");
					this.OnMã_giáo_viênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngày sinh]", Storage="_Ngày_sinh", DbType="DateTime NOT NULL")]
		public System.DateTime Ngày_sinh
		{
			get
			{
				return this._Ngày_sinh;
			}
			set
			{
				if ((this._Ngày_sinh != value))
				{
					this.OnNgày_sinhChanging(value);
					this.SendPropertyChanging();
					this._Ngày_sinh = value;
					this.SendPropertyChanged("Ngày_sinh");
					this.OnNgày_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Giới tính]", Storage="_Giới_tính", DbType="Bit NOT NULL")]
		public bool Giới_tính
		{
			get
			{
				return this._Giới_tính;
			}
			set
			{
				if ((this._Giới_tính != value))
				{
					this.OnGiới_tínhChanging(value);
					this.SendPropertyChanging();
					this._Giới_tính = value;
					this.SendPropertyChanged("Giới_tính");
					this.OnGiới_tínhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Hộ khẩu thường trú]", Storage="_Hộ_khẩu_thường_trú", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Hộ_khẩu_thường_trú
		{
			get
			{
				return this._Hộ_khẩu_thường_trú;
			}
			set
			{
				if ((this._Hộ_khẩu_thường_trú != value))
				{
					this.OnHộ_khẩu_thường_trúChanging(value);
					this.SendPropertyChanging();
					this._Hộ_khẩu_thường_trú = value;
					this.SendPropertyChanged("Hộ_khẩu_thường_trú");
					this.OnHộ_khẩu_thường_trúChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Họ và tên cha]", Storage="_Họ_và_tên_cha", DbType="NVarChar(50)")]
		public string Họ_và_tên_cha
		{
			get
			{
				return this._Họ_và_tên_cha;
			}
			set
			{
				if ((this._Họ_và_tên_cha != value))
				{
					this.OnHọ_và_tên_chaChanging(value);
					this.SendPropertyChanging();
					this._Họ_và_tên_cha = value;
					this.SendPropertyChanged("Họ_và_tên_cha");
					this.OnHọ_và_tên_chaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nghề nghiệp cha]", Storage="_Nghề_nghiệp_cha", DbType="NVarChar(50)")]
		public string Nghề_nghiệp_cha
		{
			get
			{
				return this._Nghề_nghiệp_cha;
			}
			set
			{
				if ((this._Nghề_nghiệp_cha != value))
				{
					this.OnNghề_nghiệp_chaChanging(value);
					this.SendPropertyChanging();
					this._Nghề_nghiệp_cha = value;
					this.SendPropertyChanged("Nghề_nghiệp_cha");
					this.OnNghề_nghiệp_chaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Họ và tên mẹ]", Storage="_Họ_và_tên_mẹ", DbType="NVarChar(50)")]
		public string Họ_và_tên_mẹ
		{
			get
			{
				return this._Họ_và_tên_mẹ;
			}
			set
			{
				if ((this._Họ_và_tên_mẹ != value))
				{
					this.OnHọ_và_tên_mẹChanging(value);
					this.SendPropertyChanging();
					this._Họ_và_tên_mẹ = value;
					this.SendPropertyChanged("Họ_và_tên_mẹ");
					this.OnHọ_và_tên_mẹChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nghề nghiệp mẹ]", Storage="_Nghề_nghiệp_mẹ", DbType="NVarChar(50)")]
		public string Nghề_nghiệp_mẹ
		{
			get
			{
				return this._Nghề_nghiệp_mẹ;
			}
			set
			{
				if ((this._Nghề_nghiệp_mẹ != value))
				{
					this.OnNghề_nghiệp_mẹChanging(value);
					this.SendPropertyChanging();
					this._Nghề_nghiệp_mẹ = value;
					this.SendPropertyChanged("Nghề_nghiệp_mẹ");
					this.OnNghề_nghiệp_mẹChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Sổ hộ nghèo]", Storage="_Sổ_hộ_nghèo", DbType="Bit NOT NULL")]
		public bool Sổ_hộ_nghèo
		{
			get
			{
				return this._Sổ_hộ_nghèo;
			}
			set
			{
				if ((this._Sổ_hộ_nghèo != value))
				{
					this.OnSổ_hộ_nghèoChanging(value);
					this.SendPropertyChanging();
					this._Sổ_hộ_nghèo = value;
					this.SendPropertyChanged("Sổ_hộ_nghèo");
					this.OnSổ_hộ_nghèoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Khuyết tật]", Storage="_Khuyết_tật", DbType="Bit NOT NULL")]
		public bool Khuyết_tật
		{
			get
			{
				return this._Khuyết_tật;
			}
			set
			{
				if ((this._Khuyết_tật != value))
				{
					this.OnKhuyết_tậtChanging(value);
					this.SendPropertyChanging();
					this._Khuyết_tật = value;
					this.SendPropertyChanged("Khuyết_tật");
					this.OnKhuyết_tậtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGHOCSINH_BANGDIEM", Storage="_BANGDIEMs", ThisKey="Mã_học_sinh", OtherKey="Mã_học_sinh")]
		public EntitySet<BANGDIEM> BANGDIEMs
		{
			get
			{
				return this._BANGDIEMs;
			}
			set
			{
				this._BANGDIEMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGLOPHOC_BANGHOCSINH", Storage="_BANGLOPHOC", ThisKey="Mã_lớp", OtherKey="Mã_lớp", IsForeignKey=true)]
		public BANGLOPHOC BANGLOPHOC
		{
			get
			{
				return this._BANGLOPHOC.Entity;
			}
			set
			{
				BANGLOPHOC previousValue = this._BANGLOPHOC.Entity;
				if (((previousValue != value) 
							|| (this._BANGLOPHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANGLOPHOC.Entity = null;
						previousValue.BANGHOCSINHs.Remove(this);
					}
					this._BANGLOPHOC.Entity = value;
					if ((value != null))
					{
						value.BANGHOCSINHs.Add(this);
						this._Mã_lớp = value.Mã_lớp;
					}
					else
					{
						this._Mã_lớp = default(string);
					}
					this.SendPropertyChanged("BANGLOPHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGDIEMs(BANGDIEM entity)
		{
			this.SendPropertyChanging();
			entity.BANGHOCSINH = this;
		}
		
		private void detach_BANGDIEMs(BANGDIEM entity)
		{
			this.SendPropertyChanging();
			entity.BANGHOCSINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGKHOI")]
	public partial class BANGKHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_khối;
		
		private string _Tên_khối;
		
		private EntitySet<BANGLOPHOC> _BANGLOPHOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_khốiChanging(string value);
    partial void OnMã_khốiChanged();
    partial void OnTên_khốiChanging(string value);
    partial void OnTên_khốiChanged();
    #endregion
		
		public BANGKHOI()
		{
			this._BANGLOPHOCs = new EntitySet<BANGLOPHOC>(new Action<BANGLOPHOC>(this.attach_BANGLOPHOCs), new Action<BANGLOPHOC>(this.detach_BANGLOPHOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã khối]", Storage="_Mã_khối", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_khối
		{
			get
			{
				return this._Mã_khối;
			}
			set
			{
				if ((this._Mã_khối != value))
				{
					this.OnMã_khốiChanging(value);
					this.SendPropertyChanging();
					this._Mã_khối = value;
					this.SendPropertyChanged("Mã_khối");
					this.OnMã_khốiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên khối]", Storage="_Tên_khối", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Tên_khối
		{
			get
			{
				return this._Tên_khối;
			}
			set
			{
				if ((this._Tên_khối != value))
				{
					this.OnTên_khốiChanging(value);
					this.SendPropertyChanging();
					this._Tên_khối = value;
					this.SendPropertyChanged("Tên_khối");
					this.OnTên_khốiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGKHOI_BANGLOPHOC", Storage="_BANGLOPHOCs", ThisKey="Mã_khối", OtherKey="Mã_khối")]
		public EntitySet<BANGLOPHOC> BANGLOPHOCs
		{
			get
			{
				return this._BANGLOPHOCs;
			}
			set
			{
				this._BANGLOPHOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGLOPHOCs(BANGLOPHOC entity)
		{
			this.SendPropertyChanging();
			entity.BANGKHOI = this;
		}
		
		private void detach_BANGLOPHOCs(BANGLOPHOC entity)
		{
			this.SendPropertyChanging();
			entity.BANGKHOI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGLOPHOC")]
	public partial class BANGLOPHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_lớp;
		
		private string _Tên_lớp;
		
		private string _Mã_giáo_viên;
		
		private string _Mã_khối;
		
		private EntitySet<BANGHOCSINH> _BANGHOCSINHs;
		
		private EntityRef<BANGGIAOVIEN> _BANGGIAOVIEN;
		
		private EntityRef<BANGKHOI> _BANGKHOI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_lớpChanging(string value);
    partial void OnMã_lớpChanged();
    partial void OnTên_lớpChanging(string value);
    partial void OnTên_lớpChanged();
    partial void OnMã_giáo_viênChanging(string value);
    partial void OnMã_giáo_viênChanged();
    partial void OnMã_khốiChanging(string value);
    partial void OnMã_khốiChanged();
    #endregion
		
		public BANGLOPHOC()
		{
			this._BANGHOCSINHs = new EntitySet<BANGHOCSINH>(new Action<BANGHOCSINH>(this.attach_BANGHOCSINHs), new Action<BANGHOCSINH>(this.detach_BANGHOCSINHs));
			this._BANGGIAOVIEN = default(EntityRef<BANGGIAOVIEN>);
			this._BANGKHOI = default(EntityRef<BANGKHOI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã lớp]", Storage="_Mã_lớp", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_lớp
		{
			get
			{
				return this._Mã_lớp;
			}
			set
			{
				if ((this._Mã_lớp != value))
				{
					this.OnMã_lớpChanging(value);
					this.SendPropertyChanging();
					this._Mã_lớp = value;
					this.SendPropertyChanged("Mã_lớp");
					this.OnMã_lớpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên lớp]", Storage="_Tên_lớp", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Tên_lớp
		{
			get
			{
				return this._Tên_lớp;
			}
			set
			{
				if ((this._Tên_lớp != value))
				{
					this.OnTên_lớpChanging(value);
					this.SendPropertyChanging();
					this._Tên_lớp = value;
					this.SendPropertyChanged("Tên_lớp");
					this.OnTên_lớpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã giáo viên]", Storage="_Mã_giáo_viên", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_giáo_viên
		{
			get
			{
				return this._Mã_giáo_viên;
			}
			set
			{
				if ((this._Mã_giáo_viên != value))
				{
					this.OnMã_giáo_viênChanging(value);
					this.SendPropertyChanging();
					this._Mã_giáo_viên = value;
					this.SendPropertyChanged("Mã_giáo_viên");
					this.OnMã_giáo_viênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã khối]", Storage="_Mã_khối", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Mã_khối
		{
			get
			{
				return this._Mã_khối;
			}
			set
			{
				if ((this._Mã_khối != value))
				{
					this.OnMã_khốiChanging(value);
					this.SendPropertyChanging();
					this._Mã_khối = value;
					this.SendPropertyChanged("Mã_khối");
					this.OnMã_khốiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGLOPHOC_BANGHOCSINH", Storage="_BANGHOCSINHs", ThisKey="Mã_lớp", OtherKey="Mã_lớp")]
		public EntitySet<BANGHOCSINH> BANGHOCSINHs
		{
			get
			{
				return this._BANGHOCSINHs;
			}
			set
			{
				this._BANGHOCSINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGGIAOVIEN_BANGLOPHOC", Storage="_BANGGIAOVIEN", ThisKey="Mã_giáo_viên", OtherKey="Mã_giáo_viên", IsForeignKey=true)]
		public BANGGIAOVIEN BANGGIAOVIEN
		{
			get
			{
				return this._BANGGIAOVIEN.Entity;
			}
			set
			{
				BANGGIAOVIEN previousValue = this._BANGGIAOVIEN.Entity;
				if (((previousValue != value) 
							|| (this._BANGGIAOVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANGGIAOVIEN.Entity = null;
						previousValue.BANGLOPHOCs.Remove(this);
					}
					this._BANGGIAOVIEN.Entity = value;
					if ((value != null))
					{
						value.BANGLOPHOCs.Add(this);
						this._Mã_giáo_viên = value.Mã_giáo_viên;
					}
					else
					{
						this._Mã_giáo_viên = default(string);
					}
					this.SendPropertyChanged("BANGGIAOVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGKHOI_BANGLOPHOC", Storage="_BANGKHOI", ThisKey="Mã_khối", OtherKey="Mã_khối", IsForeignKey=true)]
		public BANGKHOI BANGKHOI
		{
			get
			{
				return this._BANGKHOI.Entity;
			}
			set
			{
				BANGKHOI previousValue = this._BANGKHOI.Entity;
				if (((previousValue != value) 
							|| (this._BANGKHOI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANGKHOI.Entity = null;
						previousValue.BANGLOPHOCs.Remove(this);
					}
					this._BANGKHOI.Entity = value;
					if ((value != null))
					{
						value.BANGLOPHOCs.Add(this);
						this._Mã_khối = value.Mã_khối;
					}
					else
					{
						this._Mã_khối = default(string);
					}
					this.SendPropertyChanged("BANGKHOI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGHOCSINHs(BANGHOCSINH entity)
		{
			this.SendPropertyChanging();
			entity.BANGLOPHOC = this;
		}
		
		private void detach_BANGHOCSINHs(BANGHOCSINH entity)
		{
			this.SendPropertyChanging();
			entity.BANGLOPHOC = null;
		}
	}
}
#pragma warning restore 1591
